### ISSUE TITLE
Mishandled Space with custom rule

### ISSUE THREAD

**Issue by thirtythreeforty** [cohama/lexima.vim#39]
I tried to add the following rule:

    call lexima#add_rule({'char': '<Space>', 'at': '( \+.*\%# \+)', 'leave': ' '})

This should allow me to continue typing after opening parentheses with an added space:

    foo( | )

should now become

    foo(  |)

instead of the stock behavior:

    foo(  | )

This works fine... once.  But if I have another set of parentheses with spaces *anywhere in the file* above the cursor, I cannot insert spaces in parentheses at all!  Pressing spacebar in this file does nothing:

    foo(  )
    bar(|)

This is very weird.  Does the regex match beyond the current line?

**Comment by cohama** [comment]
I could not reproduce this problem, sorry.
A vimrc you use is necessary to investigate the exact cause of that.
But, I found out a related problem and I have fixed.
Please try fix-39 branch

**Comment by thirtythreeforty** [comment]
The fix-39 branch does help somewhat.  Now, instead of being unable to type spaces at all, I can type spaces, but the spacing rules are not triggered.  That is, with the original rules applied, pressing spacebar here:

    foo(  )
    bar(|)

Now results in

    foo(  )
    bar( |)

Better, but there's still a problem.  I'll try to bisect my vimrc and see if I can nail down the reason.

**Comment by thirtythreeforty** [comment]
Update, with the following minimal `vimrc`, and with only Pathogen and Lexima.vim installed, I still have the problem I described in my previous comment.

```
set nocompatible

runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
execute pathogen#helptags()

" Extra shortcuts for lexima.vim
call lexima#add_rule({'char': ')', 'at': '(.*\%#.*)', 'leave': ')'})
call lexima#add_rule({'char': '}', 'at': '{.*\%#.*}', 'leave': '}'})
call lexima#add_rule({'char': ']', 'at': '\[.*\%#.*\]', 'leave': ']'})
"These have a bug related to not being able to type spaces.
call lexima#add_rule({'char': '<Space>', 'at': '( \+.*\%# \+)', 'leave': ' '})
call lexima#add_rule({'char': '<Space>', 'at': '{ \+.*\%# \+}', 'leave': ' '})
call lexima#add_rule({'char': '<Space>', 'at': '[ \+.*\%# \+]', 'leave': ' '})
```

This is on the fix-39 branch, commit 02efdbc140cb56f4d20362fa0f1c6522641c414a.

**Comment by cohama** [comment]
I could reproduce the problem thanks to your vimrc.
I will try to fix it.

**Comment by cohama** [comment]
I found out the exact cause of the problem.
Your `at` pattern in the last rule is treated as a collection pattern (e.g. `[a-zA-Z]`)

Try escaping `[`
```vim
call lexima#add_rule({'char': '<Space>', 'at': '\[ \+.*\%# \+]', 'leave': ' '})
```

**Comment by thirtythreeforty** [comment]
Hey, thanks for the troubleshooting. I must have missed the notification, sorry for ignoring you!  I'll try this when I get back to my computer.
